services:
  db:
    image: postgres:17-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  server:
    build: server/
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    restart: on-failure
  client:
    build: client/
    ports:
      - "3000:3000"
    volumes: 
      - ./client/src:/client/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - server
  caddy:
    image: caddy:latest
    ports:
      - "443:443"  # HTTPS port
      - "80:80"    # HTTP port pour la redirection automatique vers HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Caddyfile de configuration
      - ./client:/client  # Mount client files for Caddy
      - ./server:/server  # Mount server files if necessary
      - ./ssl:/etc/ssl/certs  # Certificat SSL (si nécessaire, Caddy gère Let's Encrypt)
    depends_on:
      - client
      - server
    restart: always